title: MyceWorld
author: MYCE
description: We help crypto users achieve successful investments by building simple blockchain-based products.

baseurl: ""

# social links
twitter_username: myceworld
github_username:  myceworld
rss: rss

show_excerpts: false

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - _pages/index.md
 - _pages/about.md
 - _pages/wallet.md
 - _pages/whitepaper.md
 - _pages/community.md

# Build settings
theme: minima
relative_permalinks: false

# Reading Files
include:
  - _pages
  - _posts
  - _wallets
  - _translations
 
# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default

plugins:
 - jekyll-feed
 - jekyll-seo-tag
